config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :movies, only: [:create, :update, :destroy, :show]

  put '/lists_movies/:list_id/:movie_id',
    controller: 'movies',
    action: :add_to_list,
    as: :add_lists_movies,
    constraints: { format: :js}

  delete '/lists_movies/:list_id/:movie_id',
    controller: 'movies',
    action: :delete_from_list,
    as: :delete_lists_movies,
    constraints: { format: :js}

  resources :lists
  get :search, to: 'search#index', as: :search
  root to: 'home#index'
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :movies, foreign_key: :imdb_id, primary_key: :imdb_id
end

app/models/list.rb
# A list represents a collection of movies for a user
# A user can have n ists containing m movies.
class List < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :movies

  validates :user, presence: true
  validates :name, presence: true, length: { minimum: 5 }

  scope :for, ->(user) { where user: user }

  # default order always starts with the one default list, then every other list by name
  default_scope { order('"default" DESC, name ASC') }

  def self.default
    find_or_initialize_by(default: true)
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  # the maximum of movies displayed intiially for a list
  MAX_DISPLAY = 5

  has_and_belongs_to_many :lists
  belongs_to :user

  validates :name, presence: true
  validates :imdb_id, presence: true

  belongs_to :dataset, foreign_key: :imdb_id, primary_key: :imdb_id

  default_scope { order('updated_at DESC')}

  scope :by, ->(user) { where user: user }

end

app/models/movie_search_result.rb
class MovieSearchResult
  attr_accessor :title, :id, :type, :synopsis

  def initialize(title:, id:, type: 'local', synopsis: nil)
    @title = title
    @id = id
    @type = type
    @synopsis = synopsis
  end

  def imdb?
    type == 'imdb'
  end

  def local?
    !imdb?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :recoverable, :rememberable, :validatable

  has_many :lists
  has_many :movies, dependent: :destroy

  after_save :create_default_list!

  private

  def create_default_list!
    list = lists.default
    return if list.persisted?
    list.name = I18n.t('.lists.default_name')
    list.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @list = List.for(current_user).new
  end

  def create
    @list = List.for(current_user).new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.for(current_user).find params[:id]
  rescue
    redirect_to lists_path
  end

  def edit
    session[:return_to] ||= request.referer
    @list = List.for(current_user).find(params[:id])
  rescue
    redirect_to lists_path
  end

  def update
    @list = List.for(current_user).find(params[:id])
    if @list.update_attributes(list_params)
      redirect_to session.delete(:return_to)
    else
      render :edit
    end
  rescue
    redirect_to lists_path
  end

  def destroy
    @list = List.for(current_user).find params[:id]
    @list.destroy!
  rescue
    render json: { error: 'Cannot delete list' }, status: :unprocessable_entity
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActionController::ParameterMissing do
    render json: {}, status: :unprocessable_entity
  end

  # aka. add to initial list
  def create
    movie, errors = AddMovieToList.for user: current_user, title: movie_title, imdb_id: imdb_id
    if errors.any?
      render json: { errors: errors }, status: :unprocessable_entity
    else
      CreateDataset.for movie
      render json: {}, status: :ok
    end
  end

  def update
    @movie = Movie.by(current_user).find(params[:id])
    if @movie.update_attributes(movie_params)
      respond_to do |format|
        format.js
      end
    end
  end

  def show
    @movie = MoviePresenter.new(Movie.by(current_user).find(params[:id]))
  end

  def destroy
    find_movie
    movie, errors = RemoveMovieFromList.for user: current_user, movie: @movie
    if errors.any?
      render json: { errors: errors }, status: :unauthorized
    else
      render json: { movie: movie }, status: :ok
    end
  end

  def add_to_list
    find_movie_and_list

    respond_to do |format|
      format.js do
        AddMovieToList.for(title: @movie.name, list: @list, imdb_id: @movie.imdb_id, user: current_user)
        @movie = MoviePresenter.new(@movie)
        render :lists_update
      end
    end
  rescue
    render json: {}, status: :unprocessable_entity
  end

  def delete_from_list
    find_movie_and_list

    respond_to do |format|
      format.js do
        RemoveMovieFromList.for(movie: @movie, list: @list, user: current_user)
        @movie = MoviePresenter.new(@movie)
        render :lists_update
      end
    end
  rescue
    render json: {}, status: :unprocessable_entity
  end

  private

  def movie_params
    params.require(:movie).permit :imdb_id, :title, :id, :notes
  end

  def list_params
    params.require(:list).permit :id
  end

  def movie_title
    movie_params.require(:title)
  end

  def imdb_id
    movie_params.require(:imdb_id)
  end

  def find_movie
    @movie = Movie.by(current_user).find_by(imdb_id: params[:id])
  end

  def find_movie_and_list
    @movie = Movie.by(current_user).find(params[:movie_id])
    @list = List.for(current_user).find(params[:list_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    return root_path unless query.present?
    search_path(m: query)
  end

  private

  def query
    params[:user][:query]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :require_query!

  def index
    @imdb_results = LookupImdbMovie.for(search_query, limit: 10)
  end

  private

  def require_query!
    @query = search_query
  end

  def search_query
    params.require(:m)
  rescue
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(_resource)
    if query.present?
      search_path(m: query)
    else
      root_path
    end
  end

  private

  def query
    return unless params[:user].present?
    params[:user][:query]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  # helper to initialize presenter over movie entries in the list
  def presentable_movies(list, no_limit = false)
    if no_limit
      movies = list.movies
    else
      movies = list.movies.limit(Movie::MAX_DISPLAY)
    end
    movies.map { |movie| MoviePresenter.new movie }
  end

  def show_more_link?(list)
    list.movies.length > Movie::MAX_DISPLAY
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def imdb_url(movie)
    if movie.is_a? MovieSearchResult
      return "http://imdb.com/title/tt#{movie.id}"
    end
    "http://imdb.com/title/tt#{movie.imdb_id}"
  end

  def optional_query
    params[:m]
  end

  def user_has_movie?(user, movie)
    id = movie.is_a?(MovieSearchResult) ? movie.id : movie.imdb_id
    user.lists.default.movies.pluck(:imdb_id).include? id
  end
end

app/views/home/_logo.html.erb
<div class="logo">
  <%# defaults for fill %>
  <% fill ||= '' %>
  <svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="31.959mm" width="149.73mm" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 535.54687 117.24218">
   <g transform="translate(-120 -435.68)">
    <g>
     <path stroke="#fff" fill="<%= fill %>" d="m227.62 435.68q7.8125 0 8.75 7.5391v0.625q0 12.461-19.297 37.07l-12.344 16.875q-12.656 17.969-14.18 26.211v1.2109q0 4.8438 6.9141 4.8438 4.0234 0 19.023-6.3281h0.27344q0.625 0.0781 0.625 0.58593v0.3125q-1.1719 3.2812-12.969 7.2266-4.8438 1.2109-6.9531 1.2109h-2.1094q-6.8359 0-9.0234-5.7422v-4.8047q2.4609-12.422 30.742-48.242 14.766-21.836 14.766-29.258v-2.1094q0-3.5938-3.9062-3.5938-11.25 0-32.852 26.211l-14.492 22.93q-8.09 16.12-9.65 18.08l-0.58594 0.3125h-0.3125q-3.3203-0.46875-3.3203-1.5234v-0.3125q0-2.5391 15.078-26.836 0-0.625 3.6328-6.9141 7.5391-14.844 7.5391-21.094 0-5.1562-2.4219-5.1562-13.281 3.5156-35.586 37.695-9.1016 13.32-18.086 24.141-5.0391 3.75-7.5391 4.2188h-2.6953q-5.8203 0-6.6406-8.75v-0.3125q0-12.617 12.656-21.992 3.1641-1.5234 4.8438-1.5234h0.27344q6.9531 0.66406 6.9531 4.2188v0.625q0 0.58594-0.625 0.58594h-2.3828q-1.6797-2.1094-3.0469-2.1094h-0.27343q-4.4531 0-11.758 11.172-2.4219 5.8984-2.4219 8.7109 0 4.0625 2.7344 6.0547h0.27343q3.9062 0 14.18-13.281 5.9766-8.0859 18.398-26.523 19.688-26.211 29.844-26.211h0.89843q6.9141 0 6.9141 7.5391 0 3.0469-1.1719 7.8125v0.3125h0.27344q10.039-12.773 20.195-18.398 5.8203-3.0078 10.859-3.3203z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m238.8 478.65q3.2812 0 7.0703 2.0312 3.3984 2.9688 3.3984 7.0703v3.5547q-0.70312 4.8438-2.8906 9.1016-2.3047 4.375-6.25 8.6328-5.2734 4.7656-8.4375 6.4062-3.8281 2.1875-8.2422 2.1875-7.5 0-10.156-5.5859-0.66406-2.5-0.66406-4.5312 0-10.391 9.4531-17.383 0-0.54688 5.0781-3.0469 3.2422-0.85937 4.5312-0.85937 4.8828 0 6.4062 2.3828v1.8359q-0.27344 0.70312-1.1719 0.70312h-0.15625l-4.0625-1.0156q-4.4922 0-11.484 6.9141l-3.0078 4.8828q-1.3672 4.2969-1.3672 5.7422v0.66406q0.89844 5.5859 5.5859 5.5859h0.15625q5.3906 0 12.812-6.9141 5.8203-5.8203 6.9141-8.9453 1.4062-1.6016 2.5391-6.6016 0.19531-0.19531 0.19531-1.1719v-2.1875q-0.85937-5.8984-5.9375-5.8984-5.3125 0-16.016 6.4062h-1.6797q-0.35156 0-0.35156-0.35156v-0.66407q1.25-3.4766 6.4062-5.8984 6.4062-3.0469 11.328-3.0469z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m285.45 472.47h1.0938q0.97656 0.54687 0.97656 1.4062v0.15625q0 2.0703-1.4453 4.4531 0 0.27344-2.1875 4.8828 0 0.54688-3.4766 6.9531-0.85938 2.8516-3.9453 8.3594 0 0.46875-3.0078 6.4844h-0.46875v0.3125q0 1.0547-1.6016 3.6328-4.1016 8.6719-7.5781 8.6719-3.8672 0-4.5703-1.7188-2.4609-4.375-2.8516-9.4922-0.78125-2.8906-1.25-11.992-0.15625 0-0.15625-0.3125 0-6.6406 1.0938-6.6406 1.0547-0.3125 1.4453-0.3125h1.5625q0.78125 0.35156 0.78125 0.78125 0 1.7578-0.3125 6.6406 0 0.66406 0.625 6.0156v1.25q1.4062 9.5703 3.0078 11.055v0.3125h0.15625q1.5234-1.3281 5.2344-8.0469 1.8359-4.2578 2.1875-4.2578l2.0703-4.4531q2.1875-3.9844 2.1875-4.4141 1.0547-1.7188 2.0703-4.4141 1.1719-1.2891 2.0312-3.6328 3.8281-7.6172 6.3281-11.68z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m313.66 449.62q4.9219 0 6.9141 5.625 0.15625 1.3672 0.15625 1.6016 0 4.6484-5.1562 6.7188-1.4062 0.3125-2.0703 0.3125-4.8438 0-6.7188-5.2734-0.15625-0.15625-0.3125-2.1094 0-4.2969 4.8047-6.4062 0.58593-0.35156 2.3828-0.46875zm-15.781 29.023h0.625q1.7578 0 1.7578 1.9531-0.23437 1.4062-3.0469 6.0547-8.5156 14.219-8.6328 21.797v0.46875q0 3.5938 3.6719 5.3125 1.1328 0.82031 1.1328 1.6016v1.2891q-0.27344 0.625-1.1328 0.625h-2.0703q-0.625-0.54687-2.5781-1.4453-3.5156-2.7344-3.5156-7.3828v-0.625q0-7.5 8.3203-21.797 4.0234-6.4844 5.4688-7.8516z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m336.71 478.84q4.3359 0 5.5078 3.5938v1.4453q0 2.6953-7.6562 9.4531-7.5 6.1719-13.633 6.1719h-2.7734q-2.3047 0-3.4375-1.9531v-1.3281q0-0.23438 0.66406-0.625h1.2891q0.66407 0 2.1484 0.3125 3.3594 0 9.4141-3.75 9.1016-7.1875 9.1016-9.7266-0.15625 0-0.15625-0.19531-10.352 0.89844-21.797 10.117-1.2109 0.89844-2.7734 2.8906-0.625 0.11719-4.2188 5.0781-5.5078 8.3594-5.5078 11.055-0.19531 0-0.19531 0.3125 0.35156 2.4219 1.7969 2.4219 5.8203-0.0391 20-8.75h1.4844q0.625 0.19531 0.625 1.4453v0.15625q0 2.5391-12.031 8.7891-4.5312 1.9531-8.125 1.9531h-0.46875q-6.1328 0-7.5-4.8828l-0.15625-1.6406q0-4.4141 5.1953-11.68 8.0078-12.305 22.461-18.398 2.7734-1.1719 8.9453-2.2656h1.7969z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m409.88 435.79q9.4141 0 12.148 6.5625 0.3125 1.25 0.3125 2.6172v1.9531q0 6.4453-13.438 18.398h-2.3047q-1.7578 0-2.3047-1.3281v-1.6406q13.789-12.188 13.789-18.359 0-3.2031-7.8906-4.2578-9.7656 0-21.953 8.8281-9.1797 8.0859-9.1797 13.789 0 6.5625 18.672 13.789 14.453 7.1875 14.453 18.047 0 9.9609-14.766 20.977-10.273 6.5625-24.609 6.5625h-2.3047q-8.5938 0-17.695-4.9219-9.8438-6.875-9.8438-16.719v-0.35156q0-14.844 18.711-24.922 6.5234-3.2812 12.773-3.2812h4.9219q-4.5703-4.8438-4.5703-9.8438v-0.625q0-12.617 22.93-23.32 5.9375-1.9531 12.148-1.9531zm-62.656 63.945q0 13.906 20 18.047 1.8359 0 4.6094 0.35156 19.375 0 32.461-16.406 2.9688-4.4531 3.6328-8.2031 0-9.375-17.734-16.094 0-0.3125-1.6406-0.97656v0.35156q2.6172 2.4219 2.6172 9.1797 0 5.5469-4.9219 8.5156h-1.2891q-0.66407 0-0.66407-0.66407v-0.97656q2.6172-6.0156 2.6172-8.8672 0-7.4609-10.508-8.8281-8.0078 0-18.672 7.8516-10.508 9.4141-10.508 16.719z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m457.51 475.44q6.0938 0 7.3828 1.875v1.2109l-0.15625 0.35157-2.0703-0.15625h-2.2266q-9.4531 0-20.781 7.8906-13.633 9.7656-17.539 20.625l-0.15625 1.7188v0.15625q0 0.9375 1.1719 1.875 6.875 0 17.539-9.7656 0.66407-0.50782 3.4375-5 7.1094-8.3594 9.6094-9.1016 0.58594-0.35156 1.0547-0.35156h0.66406q2.9297 0.70313 2.9297 2.4219v0.50781q0 1.5234-11.523 12.383-3.0859 3.2812-3.0859 8.9062v0.19531q0 4.5703 3.7891 5.3125h0.50782q4.4531 0 14.609-4.8047h0.66406q1.0547 0.15625 1.0547 0.50781v1.0156q-2.1094 2.6953-5.6641 4.2969-4.8438 2.4219-8.5938 2.4219h-2.0703q-3.3203 0-7.3828-4.1406-1.5625-3.2031-1.5625-5.8203v-1.0156h-0.15625q-7.6562 5.4688-13.242 5.4688-5.625 0-7.7344-3.9453-0.15625-0.89844-0.15625-1.7188v-1.0156q0-6.8359 10.469-17.539 16.641-14.766 29.219-14.766z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m494.66 478.49q3.4375 0 7.5781 1.8359 4.2188 2.8516 4.2188 6.7578 0.19531 0 0.35156 1.6797h0.15625q5.5859-4.375 11.992-7.2266 2.6172-1.3672 8.2812-2.2266 5.1953 0 8.0859 1.7188 3.7109 2.4219 3.7109 6.5625 0 7.4609-8.0859 15.195 0 0.54687-3.0469 3.0469-6.5625 5.8594-11.328 8.4375-4.8828 3.3594-8.75 3.3594h-0.85937q-2.6953-0.11719-2.6953-1.0156v-1.0156q0-0.39063 2.1875-1.0156 4.8438-2.2266 9.9609-5.7422 5.1953-3.75 5.2344-4.2188 4.2578-3.2422 8.7891-8.9453 3.5156-5.1562 3.5156-8.0859v-0.85937q0-3.2031-3.7109-3.2031-8.2422 0-20.234 9.6484-5.2734 4.4141-5.8984 6.7188-1.6797 3.6328-6.6016 10.977h-0.82031q-2.7734 0-4.2188-2.8516v-0.19531q0-3.7891 8.2422-13.477 1.0156-3.3984 1.0156-6.25 0-3.7891-3.2031-5.2344-1.0938-0.15625-2.1875-0.15625-3.75 0-10.117 2.8516-3.5547 1.9922-7.2656 5.2344l-4.375 4.8828q-6.25 9.375-6.25 11.172-0.58594 1.1719-1.5234 1.1719h-0.50781q-1.2109 0-2.1875-1.1719v-0.19532q0-6.4453 7.9297-16.367 8.75-9.3359 17.227-10.977l5.3906-0.82031z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m577.02 478.8q6.6406 0 9.7266 5.2734 0.625 1.3281 1.1328 4.1016v1.8359q0 9.9609-7.7344 18.594-4.4531 4.6875-9.6875 7.2266-3.9844 1.9922-9.7266 1.9922h-0.82031q-6.2109 0-7.8906-4.9609-0.15625-0.85937-0.15625-1.9531v-2.5q1.1328-5.2344 2.9297-6.4062h0.85938q1.6406 0 1.6406 1.3281v1.3281q0 0.625-0.82031 4.6094-0.19531 0.78125-0.19531 2.1094 1.0547 2.9688 4.2969 2.9688 5.3516-0.50782 10.859-4.2578 6.2891-4.9219 8.9062-9.8828 2.9297-5.7031 2.9297-10.703v-0.50782q0-3.9453-3.9453-6.0938-1.3281-0.3125-1.6406-0.3125h-1.3281q-2.7734 0-9.2188 4.1016l-5.2344 3.9453q-7.7734 7.5781-10.703 11.523-9.7266 12.773-13.672 21.406-4.375 7.1875-8.9062 19.922-1.5234 5-1.7969 5.1172-0.70312 0.3125-2.6172 0.3125h-0.66406q-0.27344 0-0.66406-0.66406v-1.4844q0.39062-4.9609 6.4062-18.242 7.2656-15 15.82-26.367 2.1484-2.9688 5.9375-7.3828 5.6641-6.4062 11.836-11.055 7.3438-4.9219 13.828-4.9219h0.3125z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m620.42 437.79h0.82032q0.35156 0.0391 0.35156 0.35156v0.66406l-0.19531 0.35156q0.27343 0 0.50781 0.50782v0.46875q0 0.50781-1.1719 2.5391 0 0.42969-2.5391 4.7266-7.1875 12.109-10.273 19.258-4.4141 8.9062-7.2656 18.906-0.27344 0-1.5234 5.5469-0.42969 2.0312-0.66406 2.0312 0 0.19531 0.15625 0.19531-1.5234 6.6406-1.5234 13.633 0.78125 5.1953 2.5391 7.1094 0.66407 0 0.66407 1.8359v0.85937q0 1.0156-3.7109 1.0156-1.4844-0.42969-2.6953-3.0469-1.6797-4.5312-1.6797-7.7734 0-7.7344 3.2031-20.078l1.6797-5.2344 2.3828-6.9141q3.3594-8.2422 8.0859-17.695 0.35156-0.27344 3.3984-6.0938 1.7578-2.9688 3.0078-4.5703 0-0.42969 2.6953-4.2188 2.0703-3.3984 3.75-4.375z"/>
     <path stroke="#fff" fill="<%= fill %>" d="m640.7 478.92h1.9531q1.9531 0 5.5469 1.7969 2.3438 2.3438 2.3438 3.9453v1.25q0 1.9922-1.0547 2.6953h-1.2891q-0.46875-0.11719-2.6562-3.9453-2.0312-1.8359-3.3984-1.9531h-1.25q-2.0703 0-5.3906 1.6016-3.125 1.2109-8.0469 6.0938-7.3438 7.8125-11.836 17.734l-3.9453 8.5938q-0.78125 1.0547-2.3047 1.0547h-0.19531q-2.8516 0-2.8516-1.6016v-0.54687q6.3281-16.094 11.641-22.188 1.4453-2.3047 4.1016-5.0391 5.4297-5.6641 10.742-7.8516 3.125-1.25 7.8906-1.6406z"/>
    </g>
   </g>
  </svg>
</div>

app/views/home/index.html.erb
<div class="intro">
  <%= render partial: 'logo' %>
  <div class="hero">
    <div class="wrapper">
      <h1 class="catchy"><%= t('.hero_intro') %> <br><small><%= t('.hero_intro_sub') %></small></h1>
    </div>
  </div>
  <div class="options">
    <div class="wrapper">
      <form action="/search" action="get" class="form">
        <label for="movie" class="control-label sr-only"><%= t('.favourite_movie') %></label>
        <input name="m" class="form-control" required type="text" id="movie" placeholder="<%= t('.favourite_movie') %>">
        <input type="submit" id="submit" class="sr-only" value="Search">
      </form>
      <% if user_signed_in? %>
        <h3 class="welcome-back"><%= t('.welcome_back') %></h3>
        <%= link_to t('.go_to_collection'), lists_path, class: 'btn btn-default', id: 'collection-link' %>
      <% else %>
        <p>
          <%= link_to t('.go_to_login'), new_user_session_path %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_app_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu">
          <span class="sr-only"><%= t('.toggle_navigation') %></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= render partial: 'home/logo', locals: { fill: '#fff' } %>
        <% end %>
      </div>

      <form class="navbar-form navbar-right" action="/search" method="get" role="search">
        <div class="form-group">
          <input type="text" name="m" value="<%= @query %>" placeholder="<%= t('.favourite_genre') %>" class="form-control">
        </div>
        <button type="submit" class="btn btn-default sr-only"><%= t('.submit') %></button>
      </form>
      <div class="collapse navbar-collapse" id="menu">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to t('.my_collection'), lists_path %>
            </li>
            <li>
              <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to t('.login_register'), new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/lists/_list.html.erb
<% full_mode ||= false %>
<div class="list" id="list-<%= list.id %>">
  <h2>
    <%= list.name %>
    <small class="actions">
      <%= link_to t('.rename'), edit_list_path(list), class: 'rename-link' %>
      <% unless list.default? %>
        | <%= link_to t('.delete'), list_path(list), data: { remote: true, method: :delete }, class: 'delete-link' %>
      <% end %>
    </small>
  </h2>
  <div class="movies">
    <% if list.movies.any? %>
      <% presentable_movies(list, full_mode).each do |movie| %>
        <%= render partial: 'movie', locals: { movie: movie } %>
      <% end %>
      <% if show_more_link?(list) && !full_mode %>
        <div class="movie more">
          <%= link_to t('.more'), list_path(list) %>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lists/_movie.html.erb
<div class="movie">
  <%= link_to movie.path do %>
    <%= image_tag movie.poster, class: 'img-responsive poster', title: movie.hint %>
    <p class="title"><%= movie.title %></p>
  <% end %>
</div>

app/views/lists/destroy.js.erb
$('#list-' + '<%= @list.id %>').fadeOut('slow', function() {
  $(this).remove();
});

app/views/lists/index.html.erb
<% content_for :header do %>
  <%= render partial: 'layouts/app_header' %>
<% end %>
<div class="lists">
  <% current_user.lists.each do |list| %>
    <%= render partial: 'list', locals: { list: list } %>
  <% end %>
</div>
<div class="actions">
  <%= link_to t('.create'), new_list_path, class: 'btn btn-default' %>
</div>

app/views/movies/update.js.erb
$('div.notes').addClass('hidden');
$('p.notes').text("<%=j @movie.notes %>").removeClass('hidden');

app/views/search/_list.html.erb
<% movies.each do |movie| %>
  <div class="movie <%= 'imdb' if movie.imdb? %>">
    <div class="movie-details">
      <h3 class="movie-title">
        <%= movie.title %>
        <% if movie.imdb? %>
          <small>
            <%= link_to t('.this_movie_on_imdb'), imdb_url(movie) %>
          </small>
        <% end %>
      </h3>
    </div>
    <div class="movie-actions">
      <% if user_signed_in? %>
        <% if user_has_movie?(current_user, movie) %>
          <%= button_tag t('.remove_from_list'), class: 'btn btn-default remove-from-default-list', data: { href: movie_path(movie.id), id: movie.id, removed: t('.removed_from_list') } %>
        <% else %>
          <%= button_tag t('.add_to_list'), class: 'btn btn-default add-to-default-list', data: { href: movies_path, id: movie.id, title: movie.title, added: t('.added_to_list') } %>
        <% end %>
      <% else %>
        <%= link_to t('.register_to_add'), new_user_registration_path(m: @query), class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
<% end %>